apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-valid
  namespace: test
  labels:
    app: not-valid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-example-app
  template:
    metadata:
      labels:
        app: opa-example-app
    spec:
      serviceAccountName: my-service-account
      containers:
        - name: opa-example-app
          # image: gcr.io/ifont/opa-example-app:latest
          image: nginx:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          securityContext:
            privileged: true
            # try omitting or set following values
            # runAsNonRoot: fasle
            # runAsUser: 0
            # runAsGroup: 0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
      - name: container-storage
        emptyDir: {}  