apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerDenyNotAllowedLabels
metadata:
  name: containerdenynotallowedlabels
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      - apps
      kinds:
      - Namespace
      - DaemonSet
      - Deployment
      - StatefulSet
    scope: Namespaced
    namespaces:
    - test
  parameters:
    labels:
      - key: app
        allowedRegex: ^valid$
