apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-example-app
  namespace: test
  labels:
    app: valid
    objectset.rio.cattle.io/hash: "71c9ae6ca6bfbc906f0c6e874adb6b18200914db"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-example-app
  template:
    metadata:
      labels:
        app: opa-example-app
    spec:
      containers:
        - name: opa-example-app
          # image: gcr.io/ifont/opa-example-app:latest
          image: nginx:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"             