apiVersion: v1
kind: Service
metadata:
  name: opa-example-app
  namespace: test
  labels:
    app: not-valid
spec:
  clusterIP: 10.43.21.196
  clusterIPs:
  - 10.43.21.196
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: svc-port-pre-nginx-port
    port: 80
    targetPort: nginx-port
    protocol: TCP
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort